### ISSUE TITLE
Set custom language has default language when the game is opening

### ISSUE THREAD

**Issue by Aldair402** [PippleCultist/HoloCureLanguagePackMod#12]
I been translating holocure to spanish but i have no way to check if the introText translation work.
So setting a custom language as a default language every time the games open would help a lot also is kinda anoying change the language in settings every time i want to check something. I tried to change the lang in Appdata but it crashes the game

**Comment by PippleCultist** [comment]
I can't really do anything about that since YYTK doesn't pause game execution, so the game intro text would actually start playing before the mod loads in. Messing with the language in appdata would also cause the game to crash since the mod hasn't loaded yet which is why I haven't implemented that. I asked the YYTK dev about this, but I'm not sure if they're planning on implementing a fix for this.

**Comment by PippleCultist** [comment]
I added saving the previously used language, but having translated intro text is going to have to wait until YYTK gets updated to pause the game when mods are loading.

**Comment by PippleCultist** [comment]
This should be fixed in v1.0.7. It's not really an elegant solution since I had to bring the game back to the very start once the mod has loaded, but it should be translating the intro text now.
